start a..z A..Z word .
start 0..9 word .
start _ gap .
start _..~ start @
start start ?

word a..z A..Z word .
word 0..9 word .
word start W

gap _ gap .
gap start _

----------
x
W
x y
WGW
xy, z
WwSGW
